### ISSUE TITLE
My phone is always awake after a commit...

### ISSUE THREAD

**Issue by gianogli** [crdroidandroid/android_frameworks_base#10]
I discovered that after you push the commit "Fix InCallActivity onStop call when launch from Lockscreen" my phone (Samsung i9300) remain always into the awake state.

With the command "dumpsys power" I found that:

******************************
Wake Locks: size=2
  PARTIAL_WAKE_LOCK              'ActivityManager-Sleep' ACQ=-14m25s604ms LONG (uid=1000 pid=2450)
  DOZE_WAKE_LOCK                 'DreamManagerService' ACQ=-14m25s227ms (uid=1000 pid=2450)
******************************

As you can see the service "ActivityManager" had a PARTIAL_WAKE_LOCK lock!

I tried to revert only the commit "Fix InCallActivity onStop call when launch from Lockscreen" from my unofficial ROM zip file and the problem is disappeared.

Could you verify this behavior?

Thanks...

**Comment by faust93** [comment]
Confirm, have same issue.

**Comment by neobuddy89** [comment]
This commit is reverted.
