### ISSUE TITLE
4G issue...

### ISSUE THREAD

**Issue by gianogli** [crdroidandroid/android_frameworks_base#11]
It seems that the commit "telephony: Add state check for LteOnCdma to isGsm and isCdma" can make LTE/4G unusable. Other ROM makers have already reverted it: [ResurrectionRemix revert](https://github.com/ResurrectionRemix/android_frameworks_base/commit/fecfcc9c57d939600e29302390b5cad02e112542)
Could you verify and revert it?

**Comment by neobuddy89** [comment]
Sorry, it got re-added by mistake while rebasing.
Will be reverted. Thanks.
