### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ieprst** [crdroidandroid/android_frameworks_base#110]
ERROR: /home/alex/crDroid/frameworks/base/core/java/android/os/Parcel.java:605.16: The method checkOffsetAndCount(int, int, int) is undefined for the type Arrays
ERROR: /home/alex/crDroid/frameworks/base/core/java/android/os/Parcel.java:634.16: The method checkOffsetAndCount(int, int, int) is undefined for the type Arrays
ERROR: /home/alex/crDroid/frameworks/base/core/java/android/os/FileBridge.java:181.20: The method checkOffsetAndCount(int, int, int) is undefined for the type Arrays
ERROR: /home/alex/crDroid/frameworks/base/core/java/android/content/pm/LimitedLengthInputStream.java:74.16: The method checkOffsetAndCount(int, int, int) is undefined for the type Arrays
ERROR: /home/alex/crDroid/frameworks/base/drm/java/android/drm/DrmOutputStream.java:94.16: The method checkOffsetAndCount(int, int, int) is undefined for the type Arrays

**Comment by gwolf2u** [comment]
commit this locally 
https://github.com/crdroidandroid/android_frameworks_base/commit/96ff29d23748627eba4fa41431a3eb15931b3d52

**Comment by gwolf2u** [comment]
added after rebase
