### ISSUE TITLE
Attestation not HARDWARE_BACKED

### ISSUE THREAD

**Issue by PlatFlat** [crdroidandroid/android_frameworks_base#1125]
Strong integrity evaluation is backed by "HARDWARE_BACKED". Therefore having PixelProps on framework (keystore/java/android/security/keystore2/AndroidKeyStoreSpi.java) is blocking HARDWARE_BACKED evaluation and is only showing basic. Original OEM OSes have these both by default. 

The specific line affecting its blocking can be found in the file "keystore/java/android/security/keystore2/AndroidKeyStoreSpi.java" - https://github.com/crdroidandroid/android_frameworks_base/blob/638ebd2240e9229353c0310ce360d17f12812fb9/keystore/java/android/security/keystore2/AndroidKeyStoreSpi.java#L198C9-L198C55 

Have a toggle option to turn on/off HARDWARE_BACKED, an [example ](https://github.com/Evolution-X/frameworks_base/blame/5e92eb1a2d2ce8cf3692490eab90aa18464bd8de/keystore/java/android/security/keystore2/AndroidKeyStoreSpi.java#L184)of how Evolution is doing the boolean option.

Note: Build also need to have [android.hardware.hardware_keystore.xml](https://cs.android.com/android/platform/superproject/main/+/main:hardware/interfaces/security/keymint/aidl/default/android.hardware.hardware_keystore.xml) in /vendor/etc/permissions.

**Comment by meiser79** [comment]
It's already there since some days. The toogle button is in crDroidSettings. The keystore.xml is not needed.

Next time, please open an issue under https://github.com/crdroidandroid/issue_tracker. Thanks!

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/9ddc536562947f1ea0f789fb237fa35c6270a808
