### ISSUE TITLE
AttestationService gmscore spoof selinux denials 

### ISSUE THREAD

**Issue by momenabdulrazek** [crdroidandroid/android_frameworks_base#1188]
in this commit of AttestationService.java: 
https://github.com/crdroidandroid/android_frameworks_base/commit/aae785539fc4092375b091ff3a6611ed8d71bab7

at line 56 : "mDataFile = new File(Environment.getDataSystemDirectory(), DATA_FILE);"

here /data/system is used for gms_certified_props.json which isn't accessible by gmscore_app and will have a denial from selinux as what showing in log:

type=1400 audit(0.0:852): avc: denied { open } for path = "/data/system/gms_certified_props.json" dev="sda32" ino=817129 scontext=u:r:gmscore_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0 app=com.google.android.gms

here sepolicy denials gmscore_app from reading and writing to /data/local and requires creation of gmscore_app.te in  sepolicy/vendor  in device tree
with property : allow gmscore_app system_data_file: file { open };

so directory must be changed to avoid such things

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_device_crdroid_sepolicy/commit/fbf573bbc711ad1e238b2fb22f7c2441918c08ad
