### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by sbwml** [crdroidandroid/android_frameworks_base#137]
[ 97% 59123/60388] Target Java: /home/cr-p/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar
Note: Generating a Provider for com.android.dialer.glidephotomanager.impl.GlidePhotoManagerImpl. Prefer to run the dagger processor over that class instead.
Note: [1] Wrote GeneratedAppGlideModule with: []
[ 97% 59126/60388] //frameworks/base/services/core:services.core.unboosted javac [common]
FAILED: /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar 
rm -rf "/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && mkdir -p "/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && /home/cr-p/out/soong/host/linux-x86/bin/zipsync -d /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars -l /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list -f "*.java"  && /home/cr-p/out/soong/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk9/linux-x86/bin/javac -J-Xmx2048M -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -bootclasspath /home/cr-p/out/soong/.intermediates/libcore/core-oj/android_common/turbine-combined/core-oj.jar:/home/cr-p/out/soong/.intermediates/libcore/core-libart/android_common/turbine-combined/core-libart.jar -classpath /home/cr-p/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:/home/cr-p/out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:/home/cr-p/out/soong/.intermediates/external/okhttp/okhttp/android_common/turbine-jarjar/okhttp.jar:/home/cr-p/out/soong/.intermediates/frameworks/base/services/net/services.net/android_common/turbine-combined/services.net.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/light/2.0/android.hardware.light-V2.0-java/android_common/turbine-combined/android.hardware.light-V2.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/power/1.0/android.hardware.power-V1.0-java/android_common/turbine-combined/android.hardware.power-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/tv/cec/1.0/android.hardware.tv.cec-V1.0-java/android_common/turbine-combined/android.hardware.tv.cec-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/system/libhidl/transport/manager/1.0/android.hidl.manager-V1.0-java/android_common/turbine-combined/android.hidl.manager-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/lineage-sdk/org.lineageos.platform.internal/android_common/turbine-combined/org.lineageos.platform.internal.jar:/home/cr-p/out/soong/.intermediates/system/timezone/distro/core/time_zone_distro/android_common/turbine-combined/time_zone_distro.jar:/home/cr-p/out/soong/.intermediates/system/timezone/distro/installer/time_zone_distro_installer/android_common/turbine-combined/time_zone_distro_installer.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/authsecret/1.0/android.hardware.authsecret-V1.0-java/android_common/turbine-combined/android.hardware.authsecret-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/broadcastradio/2.0/android.hardware.broadcastradio-V2.0-java/android_common/turbine-combined/android.hardware.broadcastradio-V2.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/health/1.0/android.hardware.health-V1.0-java/android_common/turbine-combined/android.hardware.health-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/health/2.0/android.hardware.health-V2.0-java/android_common/turbine-combined/android.hardware.health-V2.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/weaver/1.0/android.hardware.weaver-V1.0-java/android_common/turbine-combined/android.hardware.weaver-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.1/android.hardware.biometrics.fingerprint-V2.1-java/android_common/turbine-combined/android.hardware.biometrics.fingerprint-V2.1-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/oemlock/1.0/android.hardware.oemlock-V1.0-java/android_common/turbine-combined/android.hardware.oemlock-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/tetheroffload/control/1.0/android.hardware.tetheroffload.control-V1.0-java/android_common/turbine-combined/android.hardware.tetheroffload.control-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/vibrator/1.0/android.hardware.vibrator-V1.0-java/android_common/turbine-combined/android.hardware.vibrator-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/configstore/1.0/android.hardware.configstore-V1.0-java/android_common/turbine-combined/android.hardware.configstore-V1.0-java.jar:/home/cr-p/out/soong/.intermediates/hardware/interfaces/contexthub/1.0/android.hardware.contexthub-V1.0-java/android_common/turbine-combined/android.hardware.contexthub-V1.0-java.jar -source 1.8 -target 1.8 -d /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -s /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno @/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp @/home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list && /home/cr-p/out/soong/host/linux-x86/bin/soong_zip -jar -o /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar -C /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -D /home/cr-p/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2327: error: method fdeChangePassword in interface IVold cannot be applied to given types;
            mVold.fdeChangePassword(type, currentPassword, password);
                 ^
  required: int,String
  found: int,String,String
  reason: actual and formal argument lists differ in length
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2538: error: cannot find symbol
            mVold.clearUserKeyAuth(userId, serialNumber, encodeBytes(token), encodeBytes(secret));
                 ^
  symbol:   method clearUserKeyAuth(int,int,String,String)
  location: variable mVold of type IVold
2 errors
[ 97% 59129/60388] ----- Making recovery image ------

**Comment by sbwml** [comment]
What is the reason for this?

**Comment by neobuddy89** [comment]
You need to repopick commits from below topics:
https://review.lineageos.org/#/q/status:open+topic:pie-hw-fde
https://review.lineageos.org/#/q/status:open+topic:fbe-wrapped-key
