### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by 1582130940** [crdroidandroid/android_frameworks_base#170]
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2328: error: method fdeChangePassword in interface IVold cannot be applied to given types;
            mVold.fdeChangePassword(type, currentPassword, password);
                 ^
  required: int,String
  found: int,String,String
  reason: actual and formal argument lists differ in length
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2539: error: cannot find symbol
            mVold.clearUserKeyAuth(userId, serialNumber, encodeBytes(token), encodeBytes(secret));
                 ^
  symbol:   method clearUserKeyAuth(int,int,String,String)
  location: variable mVold of type IVold
2 errors

The commits in these two reviews are not fully merged.
https://review.lineageos.org/#/q/status:open+topic:pie-hw-fde
https://review.lineageos.org/#/q/status:open+topic:fbe-wrapped-key

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android/commit/837800d6309eddb374952e2af27a83586bd5b704

repopick missing ones from LOS. We are still in beta phase.

**Comment by soubhik-khan** [comment]
@1582130940 sync and build now again.. added the required stuffs
