### ISSUE TITLE
error: method fdeChangePassword

### ISSUE THREAD

**Issue by evnit** [crdroidandroid/android_frameworks_base#173]
ase/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp @/media/root/x/crdroid/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list && /media/root/x/crdroid/out/soong/host/linux-x86/bin/soong_zip -jar -o /media/root/x/crdroid/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar -C /media/root/x/crdroid/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -D /media/root/x/crdroid/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2328: error: method fdeChangePassword in interface IVold cannot be applied to given types;
            mVold.fdeChangePassword(type, currentPassword, password);
                 ^
  required: int,String
  found: int,String,String
  reason: actual and formal argument lists differ in length
frameworks/base/services/core/java/com/android/server/StorageManagerService.java:2539: error: cannot find symbol
            mVold.clearUserKeyAuth(userId, serialNumber, encodeBytes(token), encodeBytes(secret));
                 ^
  symbol:   method clearUserKeyAuth(int,int,String,String)
  location: variable mVold of type IVold

**Comment by neobuddy89** [comment]
You need to track our manifest with 
https://github.com/crdroidandroid/android/commit/837800d6309eddb374952e2af27a83586bd5b704

**Comment by evnit** [comment]
But now have 3 errors:
system/vold/KeyStorage.cpp:141:65: error: no member named 'KM_TAG_FBE_ICE' in namespace 'android::hardware::keymaster::V4_0'
    param1.tag = (km::Tag) (android::hardware::keymaster::V4_0::KM_TAG_FBE_ICE);
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
system/vold/KeyStorage.cpp:147:69: error: no member named 'KM_TAG_KEY_TYPE' in namespace 'android::hardware::keymaster::V4_0'
        param2.tag = (km::Tag) (android::hardware::keymaster::V4_0::KM_TAG_KEY_TYPE);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
system/vold/KeyStorage.cpp:150:69: error: no member named 'KM_TAG_KEY_TYPE' in namespace 'android::hardware::keymaster::V4_0'
        param2.tag = (km::Tag) (android::hardware::keymaster::V4_0::KM_TAG_KEY_TYPE);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
3 errors generated.

Please help me
