### ISSUE TITLE
Laggy notification swipe animation

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#226]
When you swipe away a notification, the animation is very laggy.

adb logcat doesn't say anything. The last build that doesn't have the problem is the one from 18.04.

**Comment by neobuddy89** [comment]
Can't reproduce.

**Comment by tkchn** [comment]
Might be a notch related issue since it started happening right after the notch-related commits (e.g. https://github.com/crdroidandroid/android_frameworks_base/commit/2a7e13df4a77457fa2fd7d1078712ac206e3096e)
