### ISSUE TITLE
notifications issue 

### ISSUE THREAD

**Issue by gwolf2u** [crdroidandroid/android_frameworks_base#230]
https://github.com/crdroidandroid/android_frameworks_base/commit/d44b78c073b0c306b36ca166fafdb1474bfad414 
causes notifications to not show in notifications shade even if vibration and sound for notifications pass through 
removed in fwb test branch and all is good 

steps to reproduce:
1. get a notification and dismiss it 
2. lock screen and wait 2-3 seconds and unlock 
3. get another notification (this time no longer visible on notification shade)

tested on beryllium 
might interfere with some other settings (maybe, don't know)
just got GPS off. weather toggle is off also not using crDroid Home

**Comment by neobuddy89** [comment]
Unable to reproduce - however, pushed some fix to make it less invasive:
https://github.com/crdroidandroid/android_frameworks_base/commit/25d1052c32c128f6ef57c19eb18ef3f2ee9f4c0c

**Comment by gwolf2u** [comment]
Closed
Fixed by https://github.com/crdroidandroid/android_frameworks_base/commit/25d1052c32c128f6ef57c19eb18ef3f2ee9f4c0c

**Comment by gwolf2u** [comment]
issue reoccurs after May rebase
happens when lockscreen weather toggle is on (note that my location is off so no use of WeatherClient in this case I guess)
reverted https://github.com/crdroidandroid/android_frameworks_base/commit/e931b6821aad92d304ca4a3c080d094bfa41c9f9 and https://github.com/crdroidandroid/android_frameworks_base/commit/f9fbe50af279d655eeef1b7204d7bd96d5e137ca and all seems fine now 
temp fix in fwb 9.0-fixes branch

**Note**: Launcher3 also needs 9.0-fixes branch
