### ISSUE TITLE
multiuser support

### ISSUE THREAD

**Issue by fantastory** [crdroidandroid/android_frameworks_base#244]
Would it be possible to allow mutliuser support?
according to
https://source.android.com/devices/tech/admin/multi-user

It is not enabled here
https://raw.githubusercontent.com/crdroidandroid/android_frameworks_base/9.0/core/res/res/values/config.xml

currently:
```
<!-- Maximum number of supported users -->
<integer name="config_multiuserMaximumUsers">1</integer>

<!-- Maximum number of users we allow to be running at a time -->
<integer name="config_multiuserMaxRunningUsers">3</integer>

<!-- Whether UI for multi user should be shown -->
<bool name="config_enableMultiUserUI">false</bool>
```

**Comment by neobuddy89** [comment]
It is enabled via overlay.
https://github.com/crdroidandroid/android_vendor_crdroid/blob/9.0/overlay/common/frameworks/base/core/res/res/values/config.xml#L92
