### ISSUE TITLE
Phone ringing not routed to Speaker when connected to Bluetooth 

### ISSUE THREAD

**Issue by kesavanm** [crdroidandroid/android_frameworks_base#245]
Hi Team - Thanks for doing great job.

**Reported on** : `Android Pie` as well as  `LineageOS 16`
**Verified in**  : `crDroid 5.4`
**Device** : `sakura`  aka **Redmi 6 Pro**
**Issue**  : Phone ringing not routed to Speaker when connected to Bluetooth
**Detail**  :  Phone is connected with bluetooth devices (Bluedio , MPOW) . On receiving a new phone call on telephony, the audio not routed on both Phone Speaker as well as Bluetooth device. 
**What works** : `Vibration` works as expected

Share any workaround and confirm it's a bug with core AOSP

**Comment by gwolf2u** [comment]
needs fixes from LOS

**Comment by kesavanm** [comment]
Are you able to replicate the bug ? Aware of any open bug on LOS?
