### ISSUE TITLE
Q Clock strings not translated in ROM, although in source translated

### ISSUE THREAD

**Issue by Vladislav4KZ** [crdroidandroid/android_frameworks_base#283]
Language: Russian (Region: Russia)
Device: Xiaomi Redmi Note 3 Pro Prime (kenzo)
ROM Maintainer: Aman Singh @amanraj007
Last build: 15 July 2019

**Comment by neobuddy89** [comment]
We have improvised Q Clock implementation in crDroid Pie for localization. Translations for Q Clock were reset on 24th July for all languages - please do submit new translations if you wish to see in next update for your device. Cheers.

https://crowdin.com/project/crdroid-frameworks-base
