### ISSUE TITLE
Bluetooth in version 3.8.4 does not transmit only receives data.On firmware version 3.4 was the same

### ISSUE THREAD

**Issue by lunik1981** [crdroidandroid/android_frameworks_base#31]
Bluetooth in version 3.8.4 does not transmit only receives data.On firmware version 3.4 was the same

**Comment by neobuddy89** [comment]
This should be device specific issue.

**Comment by lunik1981** [comment]
ResurrectionRemix -Ok
LineageOS- Ок
crdroidandroid -NO
All MTK and Xiaomi. Redmi 4X    Xiaomi Redmi Note 4

**Comment by neobuddy89** [comment]
Logs pls,

**Comment by lunik1981** [comment]
![screenshot_20171212-163103](https://user-images.githubusercontent.com/25451991/33887299-63a5f9a2-df5a-11e7-9abe-287bc768cca8.png)
1.1 megabyte transfers

![screenshot_20171212-163042](https://user-images.githubusercontent.com/25451991/33887372-9fdd0b7c-df5a-11e7-8fab-aec7ef616fce.png)
3.06 MB does not pass

**Comment by lunik1981** [comment]
Log https://gist.github.com/lunik1981/ddd6f7b5ea59ddae6f818662e7583f42

**Comment by lunik1981** [comment]
Will there be a solution?

**Comment by lunik1981** [comment]
build.board: mt6735
build.bootloader: unknown
build.brand: Wileyfox
build.cpu_abi: arm64-v8a
build.cpu_abi2:
build.device: porridge
build.display: NJH47D
build.fingerprint: WILEYFOX/porridge:7.1.2/NJH47D/4f152a282c:userdebug/release-keys
build.hardware: mt6735
build.host: alt
build.id: NJH47D
build.manufacturer: Wileyfox
build.model: Wileyfox Spark
build.product: porridge
build.radio: unknown
build.serial: WbSPARKPJJ0094744
build.tags: release-keys
build.time: 1499442466000
build.type: userdebug
build.user: alt
version.codename: REL
version.incremental: 4f152a282c
version.release: 7.1.2
version.sdk_int: 25

09-06 22:24:27.100 D/BluetoothOppReceiver(2957): Enter - onReceive for intent:android.btopp.intent.action.INCOMING_FILE_NOTIFICATION
09-06 22:24:27.100 D/BluetoothOppReceiver(2957): Receiver INCOMING_FILE_NOTIFICATION
09-06 22:24:27.107 D/BluetoothOppReceiver(2957): Exit - onReceive for intent:android.btopp.intent.action.INCOMING_FILE_NOTIFICATION
09-06 22:24:27.175 I/BluetoothOpp(2957): File Name DSC_0455
09-06 22:24:27.207 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:27.207 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:27.207 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:27.217 I/BluetoothOppNotification(2957): Incoming Notification ID :5
09-06 22:24:27.314 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:27.314 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:27.314 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:27.359 I/BluetoothOppNotification(2957): Incoming Notification ID :5
09-06 22:24:29.633 D/BluetoothOppReceiver(2957): Enter - onReceive for intent:android.btopp.intent.action.ACCEPT
09-06 22:24:29.687 D/BluetoothOppReceiver(2957): Exit - onReceive for intent:android.btopp.intent.action.ACCEPT
09-06 22:24:31.762 D/BluetoothOppReceiver(2957): Enter - onReceive for intent:android.btopp.intent.action.TRANSFER_COMPLETE
09-06 22:24:31.804 D/BluetoothOppReceiver(2957): Exit - onReceive for intent:android.btopp.intent.action.TRANSFER_COMPLETE
09-06 22:24:31.904 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:31.904 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:31.904 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:32.020 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:32.020 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:32.020 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:33.926 E/BluetoothRemoteDevices(2957): state12newState1
09-06 22:24:33.936 D/AvrcpBipRsp(2957): onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.938 D/BluetoothMapService(2957): onReceive
09-06 22:24:33.938 D/BluetoothMapService(2957): onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.938 E/BluetoothMapService(2957): Unexpected error!
09-06 22:24:33.939 D/BluetoothPbapReceiver(2957): PbapReceiver onReceive action = android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.940 D/BluetoothPbapReceiver(2957): Calling start service with action = null
09-06 22:24:33.942 I/BluetoothPbapReceiver(2957): Exit - onReceive for intent:android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.943 D/BluetoothPbapService(2957): Enter - onStartCommand for service PBAP
09-06 22:24:33.943 D/BluetoothPbapService(2957): action: android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.943 D/BluetoothPbapService(2957): Exit - onStartCommand for service PBAP

**Comment by lunik1981** [comment]
build.board: mt6735
build.bootloader: unknown
build.brand: Wileyfox
build.cpu_abi: arm64-v8a
build.cpu_abi2:
build.device: porridge
build.display: NJH47D
build.fingerprint: WILEYFOX/porridge:7.1.2/NJH47D/4f152a282c:userdebug/release-keys
build.hardware: mt6735
build.host: alt
build.id: NJH47D
build.manufacturer: Wileyfox
build.model: Wileyfox Spark
build.product: porridge
build.radio: unknown
build.serial: WbSPARKPJJ0094744
build.tags: release-keys
build.time: 1499442466000
build.type: userdebug
build.user: alt
version.codename: REL
version.incremental: 4f152a282c
version.release: 7.1.2
version.sdk_int: 25

09-06 22:24:27.100 D/BluetoothOppReceiver(2957): Enter - onReceive for intent:android.btopp.intent.action.INCOMING_FILE_NOTIFICATION
09-06 22:24:27.100 D/BluetoothOppReceiver(2957): Receiver INCOMING_FILE_NOTIFICATION
09-06 22:24:27.107 D/BluetoothOppReceiver(2957): Exit - onReceive for intent:android.btopp.intent.action.INCOMING_FILE_NOTIFICATION
09-06 22:24:27.175 I/BluetoothOpp(2957): File Name DSC_0455
09-06 22:24:27.207 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:27.207 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:27.207 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:27.217 I/BluetoothOppNotification(2957): Incoming Notification ID :5
09-06 22:24:27.314 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:27.314 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:27.314 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:27.359 I/BluetoothOppNotification(2957): Incoming Notification ID :5
09-06 22:24:29.633 D/BluetoothOppReceiver(2957): Enter - onReceive for intent:android.btopp.intent.action.ACCEPT
09-06 22:24:29.687 D/BluetoothOppReceiver(2957): Exit - onReceive for intent:android.btopp.intent.action.ACCEPT
09-06 22:24:31.762 D/BluetoothOppReceiver(2957): Enter - onReceive for intent:android.btopp.intent.action.TRANSFER_COMPLETE
09-06 22:24:31.804 D/BluetoothOppReceiver(2957): Exit - onReceive for intent:android.btopp.intent.action.TRANSFER_COMPLETE
09-06 22:24:31.904 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:31.904 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:31.904 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:32.020 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:511)
09-06 22:24:32.020 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
09-06 22:24:32.020 E/Notification(2957): at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
09-06 22:24:33.926 E/BluetoothRemoteDevices(2957): state12newState1
09-06 22:24:33.936 D/AvrcpBipRsp(2957): onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.938 D/BluetoothMapService(2957): onReceive
09-06 22:24:33.938 D/BluetoothMapService(2957): onReceive: android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.938 E/BluetoothMapService(2957): Unexpected error!
09-06 22:24:33.939 D/BluetoothPbapReceiver(2957): PbapReceiver onReceive action = android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.940 D/BluetoothPbapReceiver(2957): Calling start service with action = null
09-06 22:24:33.942 I/BluetoothPbapReceiver(2957): Exit - onReceive for intent:android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.943 D/BluetoothPbapService(2957): Enter - onStartCommand for service PBAP
09-06 22:24:33.943 D/BluetoothPbapService(2957): action: android.bluetooth.device.action.ACL_DISCONNECTED
09-06 22:24:33.943 D/BluetoothPbapService(2957): Exit - onStartCommand for service PBAP

**Comment by neobuddy89** [comment]
@beroid you have crackling device which I believe is Wileysoft - do you have any BT issue?

**Comment by beroid** [comment]
@neobuddy89 all fine

**Comment by lunik1981** [comment]
Sends the file, but could not accept them

**Comment by lunik1981** [comment]
ResurrectionRemix -Ok
LineageOS- Ок
crdroidandroid -NO
All MTK and Xiaomi. Redmi 4X Xiaomi Redmi Note 4

**Comment by gwolf2u** [comment]
main focus is on 4.0 now
