### ISSUE TITLE
frameworks/base/services/core/java/com/android/server/StorageManagerService.java error

### ISSUE THREAD

**Issue by Ray-Alfy** [crdroidandroid/android_frameworks_base#312]
not all of this comment megre:
https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/258160
plz revert

**Comment by gwolf2u** [comment]
@neobuddy89 
should we revert this (https://github.com/crdroidandroid/android_frameworks_base/commit/d1cb0c7783ac9b6f1cd27afddfb56d1062e7d0b5), or maybe should we track vold also with needed commits?
also I see we don't have the commit needed in hw interfaces too  
LOS is keeping this un-merged for now 
https://review.lineageos.org/q/topic:%2210-qcom-encryption-fbe-wrapped-key%22+(status:open%20OR%20status:merged)

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android/commit/d689a56bbea443ae4219fbd4e89f6d26ec41fd17
