### ISSUE TITLE
Bluetooth in version 3.8.4 does not transmit only receives data.On firmware version 3.4 was the same

### ISSUE THREAD

**Issue by lunik1981** [crdroidandroid/android_frameworks_base#32]
Bluetooth in version 3.8.4 does not transmit only receives data.On firmware version 3.4 was the same
Please do it

**Comment by gwolf2u** [comment]
main focus is on 8.1 branch right now 
most likely 7.x branches are now considered source closed with a possibility of security fixes to come 
therefor, this needs to be closed to make room for 8.x issues
