### ISSUE TITLE
Battery Icon Size (crdroid 6.2)

### ISSUE THREAD

**Issue by Razziell** [crdroidandroid/android_frameworks_base#342]
![b](https://user-images.githubusercontent.com/7115882/72659237-9dfe7780-39cd-11ea-8c38-a72f1378e976.png)
![Без имени](https://user-images.githubusercontent.com/7115882/72659238-9dfe7780-39cd-11ea-9258-82c44230f9ef.png)

**Comment by neobuddy89** [comment]
It's by AOSP design.

**Comment by Razziell** [comment]
Maybe it's the network icon: 1 - derp, 2 - cr
![IMG_20200118_093927_264](https://user-images.githubusercontent.com/7115882/72659805-90012480-39d6-11ea-8c12-411ed4c4deca.jpg)
![IMG_20200118_093921_666](https://user-images.githubusercontent.com/7115882/72659806-90012480-39d6-11ea-9ad5-00f32e64941f.jpg)

**Comment by gwolf2u** [comment]
this is too eye picking imo
so unless "fix" it, let's leave it be
safe to assume we can close this one with status "to be revised at a later time" if possible
