### ISSUE TITLE
 SystemUI eats 70% CPU and spams in logcat if battery percentage text is enabled

### ISSUE THREAD

**Issue by dvalter** [crdroidandroid/android_frameworks_base#372]
When battery percentage in status bar is shown, SystemUI spams the following message
```
W View    : requestLayout() improperly called by android.widget.TextView{2564cb1 V.ED..... ........ 44,0-138,120 #7f0a00a7 app:id/battery_percentage_view} during second layout pass: posting in next frame
```

Steps to reproduce:
1. Set `Battery percentage` to `Enabled` or `Battery percentage when charging` to `on`
2. Lock and switch off screen

Device: pioneer
Version: 6.3; latest binary and built from source

Looks similar to #129

**Comment by neobuddy89** [comment]
Fixed. 
https://github.com/crdroidandroid/android_frameworks_base/commit/0262ab06fdacea0d21c03946b4f92414e19529be
