### ISSUE TITLE
Aliasing around edges in rounded screens.

### ISSUE THREAD

**Issue by cuesta4** [crdroidandroid/android_frameworks_base#413]
This isn't really something I can show, but curved edge displays seem to have aliasing in the corners. This might be due to the way Xiaomi cuts their screens, but it's not present on their MIUI ROMs.

If you'd be kind, maybe adding an option to disable 2-3 rows of pixels around the screen could fix the problem?

My phone is an Mi 9 Lite. Thanks.

**Comment by spacetree1** [comment]
@coderzstas check please

**Comment by coderzstas** [comment]
> This isn't really something I can show, but curved edge displays seem to have aliasing in the corners. This might be due to the way Xiaomi cuts their screens, but it's not present on their MIUI ROMs.
> 
> If you'd be kind, maybe adding an option to disable 2-3 rows of pixels around the screen could fix the problem?
> 
> My phone is an Mi 9 Lite. Thanks.

Please close issue here , and reopen in pyxis bugtracker . Thanks. https://github.com/xiaomi-pyxis/android_build_bug-tracker
