### ISSUE TITLE
Lost root after update

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#424]
Hi folks,

I hope this is the right area for the error message/question :blush: 

After an OTA update I always lose root and get this message in TWRP

```
***********************
 Magisk addon.d failed
***********************
! Cannot find Magisk binaries - was data wiped or not decrypted?
! Reflash OTA from decrypted recovery or reflash Magisk
```

Is it normal that I have to flash Magisk manually after every OTA update?

**Comment by neobuddy89** [comment]
It's likely to be TWRP issue (data encryption?) on most devices.
Also, certain devices which have dynamic partitions - dont support backup tool. There, it will fail silently.

In any case, you need to flash everytime.
