### ISSUE TITLE
Configurable Dogbin URL

### ISSUE THREAD

**Issue by cs8898** [crdroidandroid/android_frameworks_base#458]
Is it Possible to extract the DogBin Upload URL from a Settings Page?

Related Files:
/core/java/com/android/internal/util/DogbinUtils.java

**Comment by gwolf2u** [comment]
not sure what you need here...

**Comment by cs8898** [comment]
Some String Value in the Preferences, so you can change the URL used to Upload the Log instead of beeing dependant on dog.bin

**Comment by gwolf2u** [comment]
we use only dogbin
