### ISSUE TITLE
Wrapped text in network traffic monitor

### ISSUE THREAD

**Issue by gj86** [crdroidandroid/android_frameworks_base#471]
Need to remove ``setStaticHeight(true);``
https://github.com/crdroidandroid/android_frameworks_base/blob/47498e2c4ea28627e4e33d7297f5b7361d3a2c91/packages/SystemUI/src/com/android/systemui/statusbar/policy/NetworkTraffic.java#L463

This causes network traffic monitor text to fold in 2 line.
![wrapped_traffic_monitor](https://user-images.githubusercontent.com/29265467/86032846-cd73de80-ba59-11ea-9dac-bc06186eea1c.jpg)

**Comment by gwolf2u** [comment]
I've also seen this few times

**Comment by gj86** [comment]
> I've also seen this few times

Can you share the logspam @neobuddy89 speaks of, I don't seem to get it in my build even though I don't use ``setStaticHeight(true)``.

@neobuddy89 
It was not right to delete all the comments from commit 47498e2

**Comment by neobuddy89** [comment]
![Screenshot_20200702-035056](https://user-images.githubusercontent.com/1227398/86399535-f1703380-bc96-11ea-9e74-4caf59ff90cc.jpg)

**Comment by gj86** [comment]
Fixed with this commit https://github.com/gj86/android_frameworks_base/commit/6746a90cdb4386804e80c7b40085c565878c15f8

**Comment by gj86** [comment]
@neobuddy89 @gwolf2u 
Fixed with this commit https://github.com/gj86/android_frameworks_base/commit/6746a90cdb4386804e80c7b40085c565878c15f8

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/227b8678c6ff2f6fbc84ceeea742967d6ceacb37
