### ISSUE TITLE
Warning spam

### ISSUE THREAD

**Issue by DrRamm** [crdroidandroid/android_frameworks_base#63]
Hi, is it normal that my log spammed by 
>04-02 09:00:25.032  1174  1174 W View    : requestLayout() improperly called by android.widget.TextView{e197293 V.ED..... ......ID 5,0-95,65 #7f0a005d app:id/battery_percentage_view} during layout: running second layout pass
>04-02 09:00:25.040  1174  1174 W View    : requestLayout() improperly called by android.widget.TextView{e197293 V.ED..... ......ID 5,0-95,65 #7f0a005d app:id/battery_percentage_view} during second layout pass: posting in next frame

I just enabled "show percentage"

**Comment by neobuddy89** [comment]
Should be fixed for next release:
https://github.com/crdroidandroid/android_frameworks_base/commit/7e25dfb25e37b283bd510cb0f8ffbb1cf22e564c

**Comment by DrRamm** [comment]
Thanks
