### ISSUE TITLE
Incorrect Wattage and Voltage value displayed on Samsung Galaxy S10(e/+)

### ISSUE THREAD

**Issue by luke-apk** [crdroidandroid/android_frameworks_base#644]
![image](https://user-images.githubusercontent.com/16850292/115529799-1b78fd80-a28b-11eb-8995-30a2c2e442ec.png)

See above image - the mA value is correct

**Comment by gwolf2u** [comment]
Samsung have different nodes I guess
As far as I know, we don't have overlays for this one so not easy fix
