### ISSUE TITLE
music visualizer will not shown when no (music) notification

### ISSUE THREAD

**Issue by rhjdvsgsgks** [crdroidandroid/android_frameworks_base#673]
some irregular music software(such as file manager, chatting software or video software when foreground) will not create a music notification when playing music. plus i noticed that even not a "music" notification(such as download progress/message notification) can also trigger shown of music visulizer when app is playing music, seems like it not caused by some "hard limitation". so, is it possible to show visulizer when any app playing sound through media channel?

**Comment by gwolf2u** [comment]
for now, not possible
