### ISSUE TITLE
Battery drain problem with pocket_judge 

### ISSUE THREAD

**Issue by maytinhdibo** [crdroidandroid/android_frameworks_base#678]
In kernel have a driver is **pocket_judge** (same Paranoid Android) driver.
But almost devices of crDroid missing this driver. 
PhoneWindowManager has an issue when the user turns on pocket mode, the pocket mode uses **high-performance CPU**, devices can not be deep-sleep. When turning off the screen, the battery still drains like when turning on. Overnight, devices will be a little or very hot.
In crDroid code PhoneWindowManager was changed with stock LineageOS, please just use pocket detection in **low-power mode**.
https://github.com/crdroidandroid/android_frameworks_base/blob/11.0/services/core/java/com/android/server/policy/PhoneWindowManager.java

**Comment by maytinhdibo** [comment]
@neobuddy89 I think the device update value from the proximity sensor repeats with an interval in config. This sensor is used **always** while screening off. _So, the device will not switch to deep-sleep mode._ 
**My problem-solving algorithm** is **only** when after person double tap on the screen, then turn on proximity sensor and get value. Turn off this sensor after get value is near or far. So we can check the device wake up when in the pocket or not. Instead of the sensor is read on a repeat. This algorithm uses less RAM than the old method.

**Comment by neobuddy89** [comment]
Tested on OP9Pro and Poco X2. Both devices goes to deep sleep even with Pocket Judge enabled.
