### ISSUE TITLE
status bar

### ISSUE THREAD

**Issue by Grant2k** [crdroidandroid/android_frameworks_base#68]
The percentage of battery charge disappears below 35% if the vertical battery icon in the bar inside the icon
![screenshot_settings_20180419-203130](https://user-images.githubusercontent.com/29144739/39008935-cecbac78-4412-11e8-87c7-8db264e44b51.png)

**Comment by neobuddy89** [comment]
Fixed for next 4.2 release.

https://github.com/crdroidandroid/android_frameworks_base/commit/0f09cdb11101a2fdaa5ab6f92845e1437cb1255b

**Comment by Grant2k** [comment]
updated to 4.2. Bug is not fixed

**Comment by gwolf2u** [comment]
@neobuddy89 can you check this out?

**Comment by neobuddy89** [comment]
Fix added: https://github.com/crdroidandroid/android_frameworks_base/commit/2541f182bf969e647ecb166b94fc2dcf5e1e1a41

To be tested.

**Comment by Grant2k** [comment]
Bug is not fixed

**Comment by gwolf2u** [comment]
confirmed as not fixed in 4.2 release
