### ISSUE TITLE
Dogbin instance for uploading stacktraces is down

### ISSUE THREAD

**Issue by unresolvedsymbol** [crdroidandroid/android_frameworks_base#686]
https://del.dog has been down for quite some time. Please consider hosting your own instance under a crdroid.net subdomain.
Relevant property: DogbinUtils::BASE_URL
Relevant file: https://github.com/crdroidandroid/android_frameworks_base/blob/11.0/core/java/com/android/internal/util/DogbinUtils.java

**Comment by gwolf2u** [comment]
Added infra
Needs code to get adapted
https://github.com/crdroidandroid/android_frameworks_base/commit/32159e64a1f89c77c29b686c794e56b89a29806e#diff-d97844b9675ecf47eff6d7036e34059c155ec93860246a7a3e12eb8c41a10b4d

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/e0749e354ba873189eb457a2072773d36972feb5

**Comment by unresolvedsymbol** [comment]
@neobuddy89 changes aren't functional.
Temporary solution for people chasing app crashes: Scoop and its xposed module
