### ISSUE TITLE
Feature Request: Per app volume control (Enhancement)

### ISSUE THREAD

**Issue by ExtNinja2099** [crdroidandroid/android_frameworks_base#708]
CrDroid has loads of amazing features. I came across a feature which the ROM currently doesn't have or isn't available for my supported device. It is a per app volume control feature that allows sound from two or more apps that are playing sound currently to be controlled individually. Here's a github repository that may have the feature: https://github.com/Evolution-X/frameworks_base
https://github.com/dotOS-FE/android_frameworks_base

I'm not sure if the feature is in there exactly, but it is a very convenient feature especially having control over apps when having multiple apps that are playing sound at the same time.

**Comment by xNombre** [comment]
Hello,
Feature requests aren't supported unless you come up with a working Pull Request.
Good luck! :)
