### ISSUE TITLE
SystemUI: Introduce DataSwitchTile 

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/android_frameworks_base#770]
This does not work - https://github.com/crdroidandroid/android_frameworks_base/commit/ebc8ce6d5745205a7dcfed6e7a7fab2a8abec3ea

**Comment by ShevT** [comment]
SIM1 - Tele2
SIM2 - Beeline
adb logcat | grep Tile.DataSwitchTile :
```
02-06 21:55:59.943  2330 15628 D Tile.DataSwitchTile: Enabled subID: 2
02-06 21:55:59.955  2330 15628 D Tile.DataSwitchTile: Disabled subID: 1
02-06 21:55:59.968  2330  2464 D Tile.DataSwitchTile: default data phone id=1
02-06 21:55:59.968  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-06 21:55:59.968  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:mSimCount=2
<switch>
02-06 21:56:06.156  2330 15771 D Tile.DataSwitchTile: Enabled subID: 1
02-06 21:56:06.174  2330 15771 D Tile.DataSwitchTile: Disabled subID: 2
02-06 21:56:06.186  2330  2464 D Tile.DataSwitchTile: default data phone id=0
02-06 21:56:06.186  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-06 21:56:06.186  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:mSimCount=2
```

SIM1 - Megafon
SIM2 - Beeline
adb logcat | grep Tile.DataSwitchTile :
```
02-06 22:00:59.216  2330 16736 D Tile.DataSwitchTile: Enabled subID: 0
02-06 22:00:59.226  2330 16736 D Tile.DataSwitchTile: Disabled subID: 3
02-06 22:00:59.229  2330 16736 D Tile.DataSwitchTile: Disabled subID: 2
02-06 22:00:59.242  2330  2464 D Tile.DataSwitchTile: default data phone id=2147483647
02-06 22:00:59.242  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-06 22:00:59.242  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:mSimCount=2
<switch>
02-06 22:01:01.726  2330 16752 D Tile.DataSwitchTile: Enabled subID: 3
02-06 22:01:01.730  2330 16752 D Tile.DataSwitchTile: Disabled subID: 2
02-06 22:01:01.744  2330  2464 D Tile.DataSwitchTile: default data phone id=0
02-06 22:01:01.744  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-06 22:01:01.744  2330  2464 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:mSimCount=2

```
same
SIM1 - Beeline
SIM2 - Megafon

**Comment by neobuddy89** [comment]
Working fine here.

02-07 02:01:47.086 D/Tile.DataSwitchTile(2204): phoneCount: 2
02-07 02:01:47.163 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:47.163 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:47.163 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:47.165 D/Tile.DataSwitchTile(2204): mSimReceiver:onReceive
02-07 02:01:47.260 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:47.260 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:47.260 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:47.263 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:47.263 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:47.263 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:47.265 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:47.265 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:47.265 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:47.268 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:47.268 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:47.268 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:52.360 D/Tile.DataSwitchTile(2204): phoneCount: 2
02-07 02:01:52.384 D/Tile.DataSwitchTile(2204): mSimReceiver:onReceive
02-07 02:01:52.386 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:52.386 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:52.386 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:52.404 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:52.405 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:52.405 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:52.407 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:52.407 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:52.407 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:52.409 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:52.409 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:52.409 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:01:52.410 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:01:52.410 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:01:52.410 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:01.514 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:01.514 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:01.514 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:01.518 D/Tile.DataSwitchTile(2204): mSimReceiver:onReceive
02-07 02:02:01.522 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:01.522 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:01.522 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:01.530 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:01.530 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:01.530 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:01.532 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:01.532 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:01.532 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:01.534 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:01.534 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:01.534 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:01.875 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:01.875 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:01.875 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:06.117 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:06.117 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:06.117 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:06.123 D/Tile.DataSwitchTile(2204): mSimReceiver:onReceive
02-07 02:02:06.126 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:06.126 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:06.126 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:06.134 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:06.134 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:06.134 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:06.138 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:06.138 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:06.138 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:06.140 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:06.141 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:06.141 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:06.457 D/Tile.DataSwitchTile(2204): default data phone id=0
02-07 02:02:06.457 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:06.457 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2
02-07 02:02:07.760 D/Tile.DataSwitchTile(2204): Enabled subID: 2
02-07 02:02:07.777 D/Tile.DataSwitchTile(2204): Disabled subID: 1
02-07 02:02:07.787 D/Tile.DataSwitchTile(2204): default data phone id=1
02-07 02:02:07.787 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-07 02:02:07.787 D/Tile.DataSwitchTile(2204): DataSwitchTile:updateSimCount:mSimCount=2

**Comment by ShevT** [comment]
It also works for me with other SIMs.
But, it doesn't work if the subID of the SIM is different from the dumb 1 and 2.

**Comment by neobuddy89** [comment]
Check 
https://github.com/crdroidandroid/android_frameworks_base/commit/4e7c6506c3ec58daa30d9fa7f6cbd2121e08454d

**Comment by ShevT** [comment]
This - https://github.com/crdroidandroid/android_frameworks_base/commit/4e7c6506c3ec58daa30d9fa7f6cbd2121e08454d#diff-fa7c8533eab4c0eed74a8da1d071c8461f9d6d8b44691f19e0b4ddf37c036601R197-R198
and - https://github.com/crdroidandroid/android_frameworks_base/commit/4e7c6506c3ec58daa30d9fa7f6cbd2121e08454d#diff-fa7c8533eab4c0eed74a8da1d071c8461f9d6d8b44691f19e0b4ddf37c036601R203-R204
was true. No need to swap here. 
This is how it should be:
`--- a/packages/SystemUI/src/com/android/systemui/qs/tiles/DataSwitchTile.java
+++ b/packages/SystemUI/src/com/android/systemui/qs/tiles/DataSwitchTile.java
@@ -194,14 +194,14 @@ public class DataSwitchTile extends QSTileImpl<BooleanState> {
                 break;
             case 1:
                 state.icon = ResourceIcon.get(activeSIMZero
-                        ? R.drawable.ic_qs_data_switch_2
-                        : R.drawable.ic_qs_data_switch_1);
+                        ? R.drawable.ic_qs_data_switch_1
+                        : R.drawable.ic_qs_data_switch_2);
                 state.value = false;
                 break;
             case 2:
                 state.icon = ResourceIcon.get(activeSIMZero
-                        ? R.drawable.ic_qs_data_switch_2
-                        : R.drawable.ic_qs_data_switch_1);
+                        ? R.drawable.ic_qs_data_switch_1
+                        : R.drawable.ic_qs_data_switch_2);
                 state.value = true;
                 break;
             default:
`
It remains to deal with the label of the network operator. In any case, shows Megafon

**Comment by neobuddy89** [comment]
PR fix.

**Comment by ShevT** [comment]
> it should always show opposite sim label.

Regardless of the selected network, it shows me - Megafon

**Comment by ShevT** [comment]
I added some prints:

```
--- a/packages/SystemUI/src/com/android/systemui/qs/tiles/DataSwitchTile.java
+++ b/packages/SystemUI/src/com/android/systemui/qs/tiles/DataSwitchTile.java
@@ -194,14 +194,14 @@ public class DataSwitchTile extends QSTileImpl<BooleanState> {
                 break;
             case 1:
                 state.icon = ResourceIcon.get(activeSIMZero
-                        ? R.drawable.ic_qs_data_switch_2
-                        : R.drawable.ic_qs_data_switch_1);
+                        ? R.drawable.ic_qs_data_switch_1
+                        : R.drawable.ic_qs_data_switch_2);
                 state.value = false;
                 break;
             case 2:
                 state.icon = ResourceIcon.get(activeSIMZero
-                        ? R.drawable.ic_qs_data_switch_2
-                        : R.drawable.ic_qs_data_switch_1);
+                        ? R.drawable.ic_qs_data_switch_1
+                        : R.drawable.ic_qs_data_switch_2);
                 state.value = true;
                 break;
             default:
@@ -225,6 +225,7 @@ public class DataSwitchTile extends QSTileImpl<BooleanState> {
         state.label = mContext.getString(R.string.qs_data_switch_label);
         if (mInactiveSlotName != null) {
             state.secondaryLabel = mInactiveSlotName;
+            Log.d(TAG, "mInactiveSlotName from handleUpdateState = " + mInactiveSlotName);
         }
     }

@@ -264,6 +265,7 @@ public class DataSwitchTile extends QSTileImpl<BooleanState> {
                 if (!foundActive) mInactiveSlotName = subInfo.getDisplayName().toString();
                 Log.d(TAG, "Changed subID " + subInfo.getSubscriptionId() + " to "
                     + !dataEnabled);
+                Log.d(TAG, "mInactiveSlotName from toggleMobileDataEnabled = " + mInactiveSlotName);
             }
         }
     }
```

Here is what they output: 

```
02-08 05:48:58.570  2366 13187 D Tile.DataSwitchTile: Changed subID 3 to true
02-08 05:48:58.570  2366 13187 D Tile.DataSwitchTile: mInactiveSlotName from toggleMobileDataEnabled = MegaFon
02-08 05:48:58.582  2366 13187 D Tile.DataSwitchTile: Changed subID 2 to false
02-08 05:48:58.582  2366 13187 D Tile.DataSwitchTile: mInactiveSlotName from toggleMobileDataEnabled = MegaFon
02-08 05:48:58.589  2366  2475 D Tile.DataSwitchTile: default data phone id=1
02-08 05:48:58.589  2366  2475 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-08 05:48:58.589  2366  2475 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:mSimCount=2
02-08 05:48:58.589  2366  2475 D Tile.DataSwitchTile: mInactiveSlotName from handleUpdateState = MegaFon
<cut>
02-08 05:49:14.769  2366 13283 D Tile.DataSwitchTile: Changed subID 3 to false
02-08 05:49:14.769  2366 13283 D Tile.DataSwitchTile: mInactiveSlotName from toggleMobileDataEnabled = MegaFon
02-08 05:49:14.777  2366 13283 D Tile.DataSwitchTile: Changed subID 2 to true
02-08 05:49:14.777  2366 13283 D Tile.DataSwitchTile: mInactiveSlotName from toggleMobileDataEnabled = MegaFon
02-08 05:49:14.785  2366  2475 D Tile.DataSwitchTile: default data phone id=0
02-08 05:49:14.785  2366  2475 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:simState=LOADED,LOADED
02-08 05:49:14.785  2366  2475 D Tile.DataSwitchTile: DataSwitchTile:updateSimCount:mSimCount=2
02-08 05:49:14.785  2366  2475 D Tile.DataSwitchTile: mInactiveSlotName from handleUpdateState = MegaFon
```

Those, the value of mInactiveSlotName does not change.

**Comment by ShevT** [comment]
Done - https://github.com/crdroidandroid/android_frameworks_base/pull/774

**Comment by ShevT** [comment]
1) The change of the carrier name still does not work after switching (the name of the operator SIM1 is displayed).

2) Also, after booting the device, the tile does not display the carrier's name until you make at least one toggle.

**Comment by ShevT** [comment]
Screenshots:

After the device boots up: 
https://i.postimg.cc/8Pmf00dF/Screenshot-20220209-234810-Settings.png

Switch from Megafon to Beeline:
https://i.postimg.cc/HkScp8hd/Screenshot-20220209-234838-Settings.png

Switch from Beeline to Megafon:
https://i.postimg.cc/3xr05F9t/Screenshot-20220209-234904-Settings.png

**Comment by ShevT** [comment]
I fixed it myself.
