### ISSUE TITLE
New change to fix brightness curve for some devices broke brightness curve for other devices ...

### ISSUE THREAD

**Issue by Albinoman887** [crdroidandroid/android_frameworks_base#779]
The commit in question is this : https://github.com/crdroidandroid/android_frameworks_base/commit/ef50785c531fb4d5e0db112ffcbbc38ea3531d78

Before this change the brightness slider curve was normal to me like being on stock or any other custom rom . I am currently building for the Pixel 6 pro (raven from here on out) I just noticed earlier tonight that the brightnless slider is very sensitive at the low end but then after about 65% it does nothing. I revert this commit and everything is fine. I don't see this being done elsewhere. maybe you could write an overlay for your device but I don't know if  doing this globally is the best idea... let me know if you need anything else

**Comment by gwolf2u** [comment]
removed in latest rebase
