### ISSUE TITLE
faceunlock and open cam

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/android_frameworks_base#784]
The problem is with the camera that pops out. For example OnePlus 7/7T/7TPro
1) Turn on the screen with the power button
2) Swipe the locked screen to enter the PIN
3) You need to enter the PIN quickly enough while the camera is moving out and initializing.
4) BUG: The screen is unlocked, the camera is pulled out.

**Comment by gwolf2u** [comment]
can't quite reproduce
one bug I can have is enter the pin faster than the camera pops
in that case the camera remains open

**Comment by ShevT** [comment]
> in that case the camera remains open

This is what I'm talking about.

**Comment by ShevT** [comment]
> Evolution-X-Devices/device_xiaomi_raphael@a5926ff

350 is much better. But, I still manage to dial a six-digit PIN.
