### ISSUE TITLE
SystemUI: circle below the home button icon

### ISSUE THREAD

**Issue by vladrevers** [crdroidandroid/android_frameworks_base#825]
Under the home button icon on the navigation bar, a [circle from the assistant](https://github.com/crdroidandroid/android_frameworks_base/blob/12.1/packages/SystemUI/res-pixel/drawable/halo.xml) is displayed, which becomes noticeable with a non-default style of the navigation bar

crDroid 8.4
<details>
<summary>Screenshot</summary>

![Screenshot_20220420-001511_Settings](https://user-images.githubusercontent.com/56305121/164106074-29c22b2a-2c73-4a33-bc27-d73db438ec12.png)
</details>

**Comment by spezi77** [comment]
@neobuddy89 great work!
Sorry for asking this: Any idea how to add the circle back exclusively for the default/pixel style of the navigation bar?

**Comment by neobuddy89** [comment]
@spezi77 
https://github.com/crdroidandroid/android_frameworks_base/blob/12.1/packages/SystemUI/res/drawable/ic_sysbar_home.xml

This is proper fix:
https://github.com/crdroidandroid/android_frameworks_base/commit/a5d782c131179f1492f5373b9613d11ebb1cf0ee
