### ISSUE TITLE
The brightness control moved down 

### ISSUE THREAD

**Issue by Razziell** [crdroidandroid/android_frameworks_base#83]
https://gist.github.com/Razziell/d23ff60f6305113013abf68072643f18
![photo_2018-05-10_19-55-33](https://user-images.githubusercontent.com/7115882/39882494-a7c47d82-548c-11e8-8bc4-4ad4ac8ec1df.jpg)

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/43bdf9ff6208b238d717ce472d8b2f8c7e94c7f7
