### ISSUE TITLE
More info on *job.deadline* and *job.delay* messages

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#834]
Hello everyone and sorry for bad English

I have a small request
Could you please adapt and add this patch to CrDroid?

https://github.com/Fincer/android_device_samsung_s5neolte_lineageOS/blob/main/lineage_src_root/patch_deadline-delay_alarmtags.patch

I found it here
https://forum.xda-developers.com/t/app-2-2-05-oct-v2-4-betterbatterystats.1179809/page-1890#post-85311663

while trying to figure out the cause of the battery drain.

Now every day I see something like this in full BBS log

```
Alarms
======================
android (): Wakeups: 1020 (50,0 / h)
  Alarms: 0, Intent: TIME_TICK
  Alarms: 0, Intent: com.android.server.action.NETWORK_STATS_POLL
  Alarms: 604, Intent: *job.deadline*
  Alarms: 0, Intent: *job.delay*
  Alarms: 94, Intent: DeviceIdleController.light
  Alarms: 71, Intent: DeviceIdleController.motion_registration
  Alarms: 199, Intent: WifiConnectivityManager Schedule Periodic Scan Timer
  Alarms: 0, Intent: *CountQuotaTracker.cleanup*
  Alarms: 19, Intent: NotificationHistoryDatabase.CLEANUP
  Alarms: 3, Intent: WriteBufferAlarm
  Alarms: 11, Intent: DeviceIdleController.motion
  Alarms: 0, Intent: WifiHealthMonitor Schedule Daily Detection Timer
```

I think the reason may be in some system component, selinux rules, or even with the bbs itself. Or something else. 

There are a lot of requests on the Internet for help in identifying the causes of these wakelocks and very few constructive answers. Perhaps this small change will help at least CrDroid users who are faced with something similar.

**Comment by gwolf2u** [comment]
this is device specific issue
