### ISSUE TITLE
Incorrect pinpad height when locked in landscape mode

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#861]
Steps to reproduce:

0. "Rotate lock screen" option disabled
1. Activate PIN:
Settings => Security => Screen lock => Choose a new screen lock => PIN
2. Enable Autorotate:
Settings => Display => Rotation settings => Auto-rotate screen
3. Open any app that can work landscape mode and rotate phone
4. Lock the device or wait for it to happen automatically in landscape mode
5. Wake device with power button or double tap (in landscape or portrait mode, no difference) and see wrong pinpad height

![Screenshot_20220621-195315_Settings](https://user-images.githubusercontent.com/31875619/174858048-4b21ba45-336b-4170-9cce-4c07e86b737a.png)

Normal pinpad
![Screenshot_20220621-195322_Settings](https://user-images.githubusercontent.com/31875619/174857966-72e97753-f07e-4d43-9c3e-9fc177a087d0.png)

**Comment by gwolf2u** [comment]
I have no such issue with my devices
maybe device specific issue caused by some wrong overlays?

**Comment by Vavun** [comment]
> I have no such issue with my devices maybe device specific issue caused by some wrong overlays?

Not sure.

It seems that the system chabge the height of the pinpad as if the lock screen is rotated and changes the height even if lock screen rotation is disabled.

Poco x3 NFC (surya)

What additional information should be provided?

I'm not cheating


https://user-images.githubusercontent.com/31875619/174981149-a2ec72f2-701b-4538-9113-4cdce55c7ca1.mp4

**Comment by Vavun** [comment]
Some more info.

When "Rotate lock screen" option enabled pinpad looks normal even in landscape 
![Screenshot_20220622-113201_crDroid Home](https://user-images.githubusercontent.com/31875619/174983115-1e19b25e-85ac-4af2-abb4-1fcb130464e8.png)

**Comment by ShevT** [comment]
> Steps to reproduce:
> 
>     0. "Rotate lock screen" option disabled
> 
>     1. Activate PIN:
>        Settings => Security => Screen lock => Choose a new screen lock => PIN
> 
>     2. Enable Autorotate:
>        Settings => Display => Rotation settings => Auto-rotate screen
> 
>     3. Open any app that can work landscape mode and rotate phone
> 
>     4. Lock the device or wait for it to happen automatically in landscape mode
> 
>     5. Wake device with power button or double tap (in landscape or portrait mode, no difference) and see wrong pinpad height


I confirm. I have also observed this behavior. Could not reproduce later.

**Comment by gwolf2u** [comment]
@GtrCraft any ideas?

**Comment by ShevT** [comment]
> Steps to reproduce:

Autorotate Lock screen enabled?

**Comment by ShevT** [comment]
![Screenshot_20220622-120010_Настройки crDroid](https://user-images.githubusercontent.com/4339059/174990202-2687dc97-32b2-4baa-beae-59de26ca23f3.png)

**Comment by Vavun** [comment]
> Autorotate Lock screen enabled?

Disabled.

When enabled buttons looks normal, just smaller

**Comment by ShevT** [comment]
My reproduce:
1. Activate PIN:
   Settings => Security => Screen lock => Choose a new screen lock => PIN
2. Enable Autorotate:
   Settings => Display => Rotation settings => Auto-rotate screen
3. Enable LockScreen autorotate
4. Rotate the phone horizontally. Make sure the image is rotated.
5. Turn off the screen with the power button
6. Rotate the phone vertically
7. Turn on the screen
8. Opening the PIN code entry window

**Comment by neobuddy89** [comment]
This is LOS/AOSP issue. Reproducible on LOS
Create issue here:
https://gitlab.com/LineageOS/issues/android

**Comment by neobuddy89** [comment]
https://gitlab.com/LineageOS/issues/android/-/issues/4817

They are already tracking this.
