### ISSUE TITLE
"Lock after screen timeout" option not working

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#863]
Settings => Security => Screen lock (gear) => Lock after screen timeout

It doesn't matter which delay to choose. The system locks immediately after the screen turns off and you have to go through the lock screen again.

Tested on "Pattern" and "PIN" locks.

Device [Poco X3 NFC](https://github.com/crdroidandroid/android_device_xiaomi_surya)

The problem appeared in crDroid based android 12 (clean install, full format)
On crDroid based on android 11 the setting worked fine

**Comment by ShevT** [comment]
Yes. This does not work. I confirm.

**Comment by neobuddy89** [comment]
Fixed.
