### ISSUE TITLE
Square shadow on rounded dropdown menu items

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#864]
Many system apps that are not fully adapted to the material you interface have a square shadow over rounded elements.

Basically in three dots drop down old standart menu (dialer app, messages app, clock app, calculator, even settings app ... )
 (Calendar and files apps generally have a squared menu, but this is not relevant to this problem.)

Examples (touch and hold):
![Screenshot_20220622-224104_Часы](https://user-images.githubusercontent.com/31875619/175123534-3374e3d7-f4a8-449f-83f0-51dfd8865411.png)
![Screenshot_20220622-224036_Настройки](https://user-images.githubusercontent.com/31875619/175123547-2d84e27b-4d2b-44bc-9343-b322e8c704d7.png)

Sorry if I chosed wrong repo to create issue, but this looks like a problem in shared resources/styles.

**Comment by Vavun** [comment]
> Не подтверждаю.
> 
> I do not confirm:

So strange.
Why do I have rounded menu list is settings and you have squared ? :-)

**Comment by Vavun** [comment]
> And your clock app looks different. Look at bottom elements
I got it. It is google clock on your screenshot, but in my case it has same issue
![Screenshot_20220623-101542_Часы](https://user-images.githubusercontent.com/31875619/175239108-c9dbb7b8-4971-4415-9f1a-2182dba37f4d.png)

**Comment by gwolf2u** [comment]
Can't confirm 
![Screenshot_20220623-150541_Clock](https://user-images.githubusercontent.com/877292/175294797-e71a3e98-ef5d-426e-96e1-587f126d098a.png)

**Comment by ShevT** [comment]
Now I see. Yes, there is a problem.

**Comment by Vavun** [comment]
@gwolf2u Re-open please.
Rechecked on a fresh install and problem exists.

And yes, above is a video correcting a misunderstanding

**Comment by neobuddy89** [comment]
This is LOS/AOSP issue. Reproducible on LOS
Create issue here:
https://gitlab.com/LineageOS/issues/android
