### ISSUE TITLE
Incorrect colors of some keyboard elements

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#865]
Since issues is disabled in the [LatinIME](https://github.com/crdroidandroid/android_packages_inputmethods_LatinIME) repo I will create issue here.

Material-you theme
1. Language text on space button is always light gray and it is hard to see it on a light background
2. Arrow on shift buttons is always dark grey and invisible on dark theme
3. layout selection button icon, search button icon and backspace button icon is always some kind of purple and it is hard to see on dark theme.
4. Nav panel is always black even on light theme.

![Screenshot_20220625-234338_Сервисы настроек](https://user-images.githubusercontent.com/31875619/175790825-5fb272f7-4382-405f-99fb-cca48e9f0a59.jpg)
![Screenshot_20220625-234358_Сервисы настроек](https://user-images.githubusercontent.com/31875619/175790831-851eba22-4bd3-4d3a-850c-ccc5eab3e0d6.jpg)

Some colors fixes after theme re-apply in keyboard settings, some not, dark purple replaced with light purple after dark to light theme switch and other strange things.

https://user-images.githubusercontent.com/31875619/175791102-7a7f955a-5d31-4a34-87de-0ae1034758f4.mp4

https://user-images.githubusercontent.com/31875619/175791105-00d2c185-ab33-4eaa-91f1-6a9d22266d36.mp4

Google keyboard have no such issues and looks correct

![Screenshot_20220625-234317_Сервисы настроек](https://user-images.githubusercontent.com/31875619/175790901-c36fef56-b987-41d6-8fbd-deb170e2c823.png)
![Screenshot_20220626-000131_Сервисы настроек](https://user-images.githubusercontent.com/31875619/175790905-1267228c-c320-490d-9dff-734a5e8f21c7.png)

**Comment by neobuddy89** [comment]
This theme is from LOS. Create issue here
https://gitlab.com/LineageOS/issues/android

**Comment by Vavun** [comment]
Finally I found some the time to do it.
https://gitlab.com/LineageOS/issues/android/-/issues/4993
I'm keeping my fingers crossed and I hope the lineageos devs don't miss it.
