### ISSUE TITLE
Touch indicator in screen record 

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_frameworks_base#879]
Hi

In old crdroid there was an option to make screen record with displaying every touch
It looked same as "Settings => Developer options => 
Show taps" 
![Screenshot_20220805-123751_Settings](https://user-images.githubusercontent.com/31875619/183051324-ff9ea092-5975-4464-b225-ca3ea0ac85ae.png)

Latest crdroid based on android 12* has no such option in screen record
Also even if "Show taps" enabled my taps not visible in final video file.

Is this a regression ?

 Thanks.

**Comment by gwolf2u** [comment]
we use Android 12 recorder now
that's what it has
