### ISSUE TITLE
Better sleep mode

### ISSUE THREAD

**Issue by Scooke1968** [crdroidandroid/android_frameworks_base#898]
I have a suggestion and one bug that I cant figure out.   1.  I think in bed time mode you should have full control over what stays active and on, without having to press each one individually.
So for me, I would like to configure the following to be either on or off when I select bed time mode (Or created a sleep mode)
WiFi
Data
Sensors
Bluetooth
Location
Sound
Battery saver
Sort of like an a la cart Aeroplane mode without having to press each one every time.  I would like to configure everything to be off except for WiFi so that backups can run in the night with the single press of Sleep mode or bedtime mode or another name of your choosing.  Is that possible with this ROM?

2.  The annoying issue is sometimes when I try to copy text, the options to cut/copy/paste etc does not show.  It just highlights and that's it and for the life of me I cannot figure out if it’s me or a bug.
Thank you for this wonderful ROM
Best to you all.
Steven

**Comment by gwolf2u** [comment]
Use issue tracker repo
