### ISSUE TITLE
[crDroid 9] SystemUI: Bottom of notification panel is weird

### ISSUE THREAD

**Issue by awakened1712** [crdroidandroid/android_frameworks_base#903]
![IMG_20221031_205522_964](https://user-images.githubusercontent.com/628212/199098731-14170e16-da06-4156-9876-4870ae256df3.jpg)
![IMG_20221031_205529_301](https://user-images.githubusercontent.com/628212/199098733-7363b47d-bf2b-464f-ac33-b0be28ef4751.jpg)

**Comment by songlongdaiduong** [comment]
> invalid repo to report issues

Where should it be?
