### ISSUE TITLE
[crDroid 9] SystemUI: Clock is missing in call

### ISSUE THREAD

**Issue by awakened1712** [crdroidandroid/android_frameworks_base#904]
Clock (top left) is missing

![Screenshot_20221101-095341_Calendar](https://user-images.githubusercontent.com/628212/199195666-e2fe8456-f635-4001-a227-e45ca6014e07.png)

Should be as below

![ongoing-call-chip-android-12-pixel-replaced-by-bubbles-after-february-update](https://user-images.githubusercontent.com/628212/199198350-7fba3ab6-dbcc-4737-b50f-50807c4c8f16.jpg)

**Comment by gwolf2u** [comment]
invalid repo
