### ISSUE TITLE
Bug in VoLTE & VoWiFi icons

### ISSUE THREAD

**Issue by kernelzru** [crdroidandroid/android_frameworks_base#927]
Commit "Improvements for dynamic VoLTE & VoWiFi icons" brakes icon, there is icon for one SIM only, but I have 2 sim. Reverting this commit fixed problem.

**Comment by lordgregorymsk** [comment]
Better leave feedback [here](https://github.com/crdroidandroid/issue_tracker/issues)
Also I have found similar issue report - [check this](https://github.com/crdroidandroid/issue_tracker/issues/65)
