### ISSUE TITLE
Allow spoofing device model for Netflix

### ISSUE THREAD

**Issue by Younis207** [crdroidandroid/android_frameworks_base#991]
can this commit added 
https://github.com/Project-Awaken/android_frameworks_base/commit/e6c0b4486ff514b5652b478a217bffd57d28b9ab
thanks in advance

**Comment by neobuddy89** [comment]
it's already there.
https://github.com/crdroidandroid/android_frameworks_base/commit/ecf03b980fb5cd6be3da0ed4d5226c5b84afd2d3

check before opening issue.
